# Generated by Django 4.1.5 on 2023-01-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date_joined", models.DateField()),
            ],
        ),
        migrations.RemoveField(model_name="post", name="excerpt",),
        migrations.RemoveField(model_name="post", name="tags",),
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(name="Tag",),
        migrations.AddField(
            model_name="likes",
            name="post_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog_app.post",
            ),
        ),
        migrations.AddField(
            model_name="likes",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog_app.user",
            ),
        ),
    ]
