# Generated by Django 4.1.5 on 2023-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_likes_user_remove_post_excerpt_remove_post_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="rating",
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
