# Generated by Django 4.1.5 on 2023-01-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
    ]
