# Generated by Django 4.1.5 on 2023-02-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
    ]
