# Generated by Django 4.1.5 on 2023-02-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
