# Generated by Django 4.1.5 on 2023-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_alter_likes_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
