# Generated by Django 4.1.5 on 2023-02-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_likes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
